apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-manager
  namespace: textara
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doc-manager
  template:
    metadata:
      labels:
        app: doc-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8001"
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      containers:
        - name: doc-manager
          image: ghcr.io/asabryy/doc-manager:latest
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: doc-manager-config
            - secretRef:
                name: doc-manager-secret
          readinessProbe:
            httpGet:
              path: /api/doc-manager/v1/health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/doc-manager/v1/health
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
