apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-worker
  namespace: textara
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doc-worker
  template:
    metadata:
      labels:
        app: doc-worker
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      containers:
        - name: doc-worker
          image: ghcr.io/asabryy/doc-manager:latest
          command: ["python", "-m", "app.worker.consumer"]
          envFrom:
            - configMapRef:
                name: doc-manager-config
            - secretRef:
                name: doc-manager-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
