apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      volumes:
        - name: cloudsql-key
          secret:
            secretName: cloudsql-key

      containers:
        - name: auth-service
          image: gcr.io/arabic-ocr-web-app/auth-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secrets
          readinessProbe:
            httpGet:
              path: /api/auth/v1/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/auth/v1/health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi

        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.10
          envFrom:
            - secretRef:
                name: auth-secrets
          command:
            - "/cloud_sql_proxy"
            - "-instances=$(CLOUDSQL_INSTANCE_CONNECTION_NAME)=tcp:0.0.0.0:3306"
            - "-credential_file=/secrets/cloudsql/key.json"
          volumeMounts:
            - name: cloudsql-key
              mountPath: /secrets/cloudsql
              readOnly: true
